# Base compose file defining services and their settings
# For concrete images check the evironment specific override files.
version: '3.7'

x-env-postgres: &env-postgres
  POSTGRES_DB: teststudio_lite_db
  POSTGRES_USER: teststudio_lite_db_user
  POSTGRES_PASSWORD: iqb_tba_db_password_1

x-env-initdata: &env-initdata
  SUPERUSER_NAME: super
  SUPERUSER_PASSWORD: user123
  WORKSPACE_NAME: sample_workspace

x-env-logging-conf: &env-logging-conf
  max-size: "200m"
  max-file: "10"

services:
  teststudio-lite-db:
    image: postgres:9.6
    container_name: teststudio-lite-db
    environment:
      <<: *env-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./config/sql/:/docker-entrypoint-initdb.d/

  teststudio-lite-backend:
    container_name: teststudio-lite-backend
    environment:
      <<: *env-postgres
      <<: *env-initdata
      POSTGRES_HOST: teststudio-lite-db
      POSTGRES_PORT: 5432
    depends_on:
      - teststudio-lite-db
    logging:
      options:
        <<: *env-logging-conf
    volumes:
      - itemplayers:/var/www/html/itemplayers
      - itemauthoringtools:/var/www/html/itemauthoringtools


  teststudio-lite-frontend:
    container_name: teststudio-lite-frontend
    logging:
      options:
        <<: *env-logging-conf

volumes:
  dbdata:
  itemplayers:
  itemauthoringtools:
